export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const FETCH_PROFILE_STARTED = "FETCH_PROFILE_STARTED";

export const LOGOUT = "LOGOUT";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

export const LOADING = "LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const RESET_ERROR = "RESET_ERROR";

export const SEND_RESET_CODE_SUCCESS = "SEND_RESET_CODE_SUCCESS";
export const SEND_RESET_CODE_FAILED = "SEND_RESET_CODE_FAILED";

export const VERIFY_RESET_CODE_SUCCESS = "VERIFY_RESET_CODE_SUCCESS";
export const VERIFY_RESET_CODE_FAILED = "VERIFY_RESET_CODE_FAILED";
